SET SERVEROUTPUT ON;

CREATE TABLE EMP_COMMISSION (
    EMPNO       NUMBER(4),
    ENAME       VARCHAR2(20),
    JOB         VARCHAR2(20),
    SAL         NUMBER(10,2),
    COMMISSION  NUMBER(10,2),
    DEPTNO      NUMBER(2)
);


INSERT INTO EMP_COMMISSION
VALUES (101, 'SMITH', 'CLERK', 8000, 1000, 10);

INSERT INTO EMP_COMMISSION
VALUES (102, 'ALLEN', 'SALESMAN', 12000, 2500, 20);

INSERT INTO EMP_COMMISSION
VALUES (103, 'WARD', 'SALESMAN', 11000, NULL, 20);

INSERT INTO EMP_COMMISSION
VALUES (104, 'JONES', 'MANAGER', 20000, 3000, 30);

INSERT INTO EMP_COMMISSION
VALUES (105, 'MARTIN', 'SALESMAN', 12500, NULL, 20);

COMMIT;

SELECT * FROM EMP_COMMISSION;


DECLARE

    V_EMPNO NUMBER := 103;
    V_COMMISSION NUMBER;
    NULL_COMMISSION EXCEPTION;

BEGIN

    SELECT COMMISSION
    INTO V_COMMISSION
    FROM EMP_COMMISSION
    WHERE EMPNO = V_EMPNO;

    IF V_COMMISSION IS NULL THEN
        RAISE NULL_COMMISSION;

    ELSE
        DBMS_OUTPUT.PUT_LINE(
            'Employee Number : ' || V_EMPNO
        );

        DBMS_OUTPUT.PUT_LINE(
            'Commission      : ' || V_COMMISSION
        );

    END IF;

EXCEPTION

    WHEN NULL_COMMISSION THEN

        DBMS_OUTPUT.PUT_LINE(
            'NULL_COMMISSION: Commission is NULL for Employee Number '
            || V_EMPNO
        );

    WHEN NO_DATA_FOUND THEN

        DBMS_OUTPUT.PUT_LINE(
            'NO_DATA_FOUND: Employee Number '
            || V_EMPNO
            || ' does not exist.'
        );

END;
/
